name: fenicsx-env
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  # MPI stack (mpich variant)
  - mpich
  - mpi4py
  # PETSc/SLEPc stack
  - petsc
  - petsc4py
  - slepc
  - slepc4py
  - hypre
  - parmetis
  - scalapack
  - superlu_dist
  - mumps-mpi
  - fftw
  # Gmsh (CLI + Python API)
  - gmsh
  - python-gmsh
  # FEniCSx stack
  - fenics-basix=0.9.0
  - fenics-dolfinx=0.9.0
  - fenics-ffcx=0.9.0
  - fenics-ufl
  # Usual scientific stack (unconstrained here)
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - statsmodels
